import './if-statement.js'
import './if-else-nesting.js'
import './switches.js'
import './calculator-challenge.js'
import './truthy-falsy.js'
import './logical-operator.js'
import './logical-assignment.js'
import './ternary-operator.js'